[package]
name = "rslog"
version = "0.1.0"
authors = ["Rostyslav Ivanika <Rostyslav.Ivanika@gmail.com>"]
edition = "2018"


[dependencies]
redis = "0.19.0"
log =  "0.4.11"
stderrlog = "0.5"
clap = {features = ["yaml"], version ="3.0.0-beta.2"}