[package]
name = "rsloglib"
version = "0.1.0"
authors = ["Rostyslav Ivanika <Rostyslav.Ivanika@gmail.com>"]
edition = "2018"


[dependencies]
redis = "0.19.0"
log =  "0.4.11"
serde = {version="1", features=["derive"]}
